_prefs: 
  mapid: ruthhannah.6612c939
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 15.293
  - 50.8476
  - 4
description: A monotone basemap that's easy to recolor.
format: "png8:m=h"
interactivity_layer: CD_VariablesWeb
layers: null
maxzoom: 22
minzoom: 0
name: MapboxLight_Province_CD
source: "mapbox:///mapbox.mapbox-streets-v5,ruthhannah.5314f160,ruthhannah.46a1e580"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
template: |-
  <strong>{{CDNAME}}</strong>
  <br /> <strong> Percentage 65+: </strong> {{Percent65O}}%
  <br /> <strong> Percentage 80+: </strong> {{Percent80_}}%
  <br /> <strong> Sex Ratio 65+: </strong> {{SexRatio65}}
  <br /> <strong> Sex Ratio 80+: </strong> {{SexRatio80}}
  <br /> <strong> Share of Population 65+: </strong> {{SharePop65}}%
  <br /> <strong>Old Component Ratio:</strong> {{OldCompone}}
