_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -104.4141
  - 70.3187
  - 3
description: SR80
format: "png8:m=h"
interactivity_layer: CD_Variables_short2_English
layers: 
  - landuse
  - aeroway
  - barrier_line
  - building
  - lanuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - waterway
  - water
  - CD_Variables_short2_English
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
maxzoom: 22
minzoom: 0
name: SR80
source: "mapbox:///mapbox.mapbox-streets-v5,ruthhannah.3b99cd3e"
styles: 
  - style.mss
template: |-
  <STRONG> Census Division: </STRONG>{{CDNAME}} 
  <br /> <strong> Sex Ratio Over 80: </strong> {{SR80}}