_prefs: 
  mapid: ruthhannah.ac663ec3
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 15.293
  - 50.8476
  - 4
description: A monotone basemap that's easy to recolor.
format: "png8:m=h"
interactivity_layer: CD_Variables_short2
layers: null
maxzoom: 22
minzoom: 0
name: Mapbox Light
source: "mapbox:///ruthhannah.c5d034e7,ruthhannah.c8dd71b1,ruthhannah.5cbb6327"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
template: |-
  <h3>{{CDNAME}}</h3>
   <strong> Percent Over 65: </strong> {{"P65"}}%
  <br /> <strong> Percent Over 80: </strong> {{P80}}%
  <br /> <strong> Sex Ratio Over 65: </strong> {{SR65}}
  <br /> <strong> Sex Ratio Over 80: </strong> {{SR80}}
  <br /> <strong> Share of Population Over 65: </strong> {{SP65}}%
  <br /> <strong> Old Component Ratio: </strong> {{OCDR}}
